// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw2_ef.Models;

#nullable disable

namespace cw2_ef.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20250908135803_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("cw_3f.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Dmitrij Głuchowski",
                            PublishedDate = new DateTime(2015, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Metro 2035"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Chrsitopher Paolini",
                            PublishedDate = new DateTime(2003, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Eragon"
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.R.R. Tolkien",
                            PublishedDate = new DateTime(1937, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hobbit, czyli tam i z powrotem"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
